version: '3.7'
services:
    api:
        build: ./api
        container_name: rails
        command: sh -c "rm -f tmp/pids/server.pid && bundle && bundle exec rails s -p 3000 -b '0.0.0.0'"
        stdin_open: true
        tty: true
        volumes:
            - ./api:/app
        ports:
            - "3000:3000"
        depends_on:
            - redis
            - sidekiq
            - cable
    meilisearch:
        image: getmeili/meilisearch:v0.28
        container_name: meilisearch
        ports:
            - "7700:7700"
        volumes:
            - ./api/db/meilisearch/data.ms:/meili_data/data.ms
        environment:
            - MEILI_MASTER_KEY=4f6bdbe90bcd297b6d
            - MEILI_NO_ANALYTICS=true
    sidekiq:
        build: ./api
        container_name: sidekiq
        command: sh -c "bundle && bundle exec sidekiq"
        volumes:
            - ./api:/app
        depends_on:
            - redis
    cable:
        build: ./api
        container_name: cable
        command: sh -c "rm -f tmp/pids/server.pid && puma -p 28080 cable/config.ru"
        volumes:
            - ./api:/app
        ports:
            - '28080:28080'
        depends_on:
            - redis
            - sidekiq
    redis:
        image: redis:alpine
        container_name: redis
        environment: 
            ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - "6379:6379"