require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.6
  TargetRailsVersion: 5.0

  NewCops: enable

  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - config/environments/**/*.rb
    - bin/**/*
    - vendor/**/*
    - routes.rb
    - lib/**/*.rake
    - lib/utils/conciliation.rb

  UseCache: false

Layout/DotPosition:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: true
  AllowMultipleStyles: true
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space

Layout/LineLength:
  Enabled: false

Lint/BooleanSymbol:
  Exclude:
    - db/**/*

Lint/EmptyBlock:
  Exclude:
    - db/migrate/20161109170845_load_modality_types.rb
    - db/migrate/20161121185630_setup_profiles_and_permissions.rb
    - db/migrate/20161124184158_load_countries.rb
    - db/migrate/20161124202206_load_cities.rb
    - db/migrate/20161124205044_load_sponsor_types.rb
    - db/migrate/20161205194055_load_event_types.rb
    - db/migrate/20170210184412_load_country_codes.rb
    - db/migrate/20170220193814_load_questions.rb
    - db/migrate/20170220205146_setup_event_questions.rb
    - spec/factories/*.rb

Lint/MissingSuper:
  Enabled: false

Lint/NestedMethodDefinition:
  Exclude:
    - db/migrate/20200713131626_populate_phone_country_from_trainer_users.rb
    - db/migrate/20210309033307_drop_trainer_future_revenues_table.rb

Lint/RescueException:
  Exclude:
    - db/migrate/20210908193220_add_status_column_on_customer_schedule.rb

Lint/SuppressedException:
  Exclude:
    - db/migrate/20210908193220_add_status_column_on_customer_schedule.rb

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Naming/VariableNumber:
  Enabled: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - db/migrate/20170825140427_set_kits_withdraw_date_end.rb
    - db/migrate/20170927161530_set_event_modality_hours_and_limits.rb
    - db/migrate/20180808144939_set_bin_discount_percentage.rb

Style/ExponentialNotation:
  Enabled: false

Style/FormatString:
  Exclude:
    - lib/geocoder/geocoder.rb

Style/FormatStringToken:
  Exclude:
    - lib/geocoder/geocoder.rb

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - db/**/*
    - app/views/**/*

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - db/**/*
    - config/routes.rb
  IncludedMacros:
    - post
    - get
    - put
    - patch
    - delete
  IgnoredMethods:
    - raise
    - exit
    - render
    - head
    - puts
    - prepend
    - include
    - throw
    - sleep
    - validate
    - to
    - not_to
    - eq
    - describe
    - shared_examples
    - of

Style/RaiseArgs:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/WordArray:
  Enabled: false

# Rails
Rails/CreateTableWithTimestamps:
  Exclude:
    - db/migrate/20161227203850_create_event_extras_subscriptions.rb
    - db/migrate/20170825195749_create_event_modalities_coupons.rb
    - db/migrate/20200721115306_create_rates_tags.rb
    - db/migrate/20200918163845_create_events_ongs.rb
    - db/migrate/20201007130952_create_activity_occurrences_subscriptions.rb
    - db/migrate/20210730181718_create_table_competition_matches_competition_teams.rb
    - db/migrate/20210802121142_create_table_customer_user_competition_team.rb

Rails/Delegate:
  Enabled: false

Rails/DynamicFindBy:
  AllowedReceivers:
    - PagarMe::BulkAnticipation
    - PagarMe::Recipient
    - PagarMe::Subscription
    - PagarMe::Transaction
    - PagarMe::Transfer

Rails/FilePath:
  Enabled: false

Rails/NotNullColumn:
  Exclude:
    - db/migrate/20220216213847_changes_for_frachisee_table.rb

Rails/ReversibleMigration:
  Exclude:
    - db/migrate/20170419194204_change_athlete_number_from_subscriptions.rb
    - db/migrate/20200821232142_change_status_type_on_customer_notifications.rb
    - db/migrate/20201020165422_change_bpm_avg_type.rb
    - db/migrate/20201106132347_drop_recurrency.rb
    - db/migrate/20201110225918_change_donation_value_nullable.rb
    - db/migrate/20210309033307_drop_trainer_future_revenues_table.rb
    - db/migrate/20210309204805_remove_payment_status_from_trainer_balances.rb
    - db/migrate/20210527122225_add_default_value_to_standard_regulation.rb
    - db/migrate/20210622132552_create_stores.rb
    - db/migrate/20210623191646_create_tokens.rb
    - db/migrate/20210728192048_add_credit_card_cpf_maximun_length.rb
    - db/migrate/20210903203748_add_terms_accepted_at_on_trainers_and_customers.rb
    - db/migrate/20220216213847_changes_for_frachisee_table.rb
    - db/migrate/20220322181715_alter_days_of_week_to_activity_occurrence.rb

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/20170623043131_set_initial_kit_sold_and_kit_blocked_to_kits.rb
    - db/migrate/20170623164308_configure_slug_in_events.rb
    - db/migrate/20170810172340_add_fields_to_event_extras.rb
    - db/migrate/20170810204745_add_fields_to_event_extras_subscriptions.rb
    - db/migrate/20170825140427_set_kits_withdraw_date_end.rb
    - db/migrate/20180808144939_set_bin_discount_percentage.rb
    - db/migrate/20200713121734_populate_phone_country_from_customer_users.rb
    - db/migrate/20200713131626_populate_phone_country_from_trainer_users.rb
    - db/migrate/20200808201206_adds_visible_to_customer_configs.rb
    - db/migrate/20210816140937_change_shop_cart_ref_column.rb
    - db/migrate/20210903203748_add_terms_accepted_at_on_trainers_and_customers.rb

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging

# Rspec
RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - associations
    - validations
    - callbacks
    - scopes
    - and
    - "on"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/Rails/AvoidSetupHook:
  Exclude:
    - test/**/*

RSpec/SubjectStub:
  Enabled: false
